// © 2015 George King. Permission to use this file is granted in license-qk.txt.
// This file is generated by gen-vec.py.
  
import Darwin
import SceneKit


extension V4 : VecType4, FloatVecType, CustomStringConvertible, JsonArrayInitable {
  typealias Scalar = Flt
  typealias FloatType = Flt
  typealias VSType = V4S
  typealias VDType = V4D
  typealias VU8Type = V4U8
  init(_ v: V4S) {
    self.init(Scalar(v.x), Scalar(v.y), Scalar(v.z), Scalar(v.w))
  }
  init(_ v: V4D) {
    self.init(Scalar(v.x), Scalar(v.y), Scalar(v.z), Scalar(v.w))
  }
  init(_ v: V4I) {
    self.init(Scalar(v.x), Scalar(v.y), Scalar(v.z), Scalar(v.w))
  }
  init(_ v: V4U8) {
    self.init(Scalar(v.x), Scalar(v.y), Scalar(v.z), Scalar(v.w))
  }
  init(_ v: V3, w: Scalar) {
    self.init(v.x, v.y, v.z, w)
  }
  init(jsonArray: JsonArray) throws {
    if jsonArray.count > 4 {
      throw Json.Error.excessEl(index: 4, exp: V4.self, json: jsonArray.raw)
    }
    self.init(try jsonArray.el(0).conv() as Flt, try jsonArray.el(1).conv() as Flt, try jsonArray.el(2).conv() as Flt, try jsonArray.el(3).conv() as Flt)
  }

  static let zero = V4(0, 0, 0, 0)
  static let unitX = V4(1, 0, 0, 0)
  static let unitY = V4(0, 1, 0, 0)
  static let unitZ = V4(0, 0, 1, 0)
  static let unitW = V4(0, 0, 0, 1)
  public var description: String { return "V4(\(x), \(y), \(z), \(w))" }
  var vs: V4S { return V4S(F32(x), F32(y), F32(z), F32(w)) }
  var vd: V4D { return V4D(F64(x), F64(y), F64(z), F64(w)) }
  var sqrLen: FloatType { return (FloatType(x).sqr + FloatType(y).sqr + FloatType(z).sqr + FloatType(w).sqr) }
  var aspect: FloatType { return FloatType(x) / FloatType(y) }
  var r: Scalar {
    get { return x }
    set { x = newValue }
  }
  var g: Scalar {
    get { return y }
    set { y = newValue }
  }
  var b: Scalar {
    get { return z }
    set { z = newValue }
  }
  var a: Scalar {
    get { return w }
    set { w = newValue }
  }

  var allNormal: Bool { return x.isNormal && y.isNormal && z.isNormal && w.isNormal }
  var allFinite: Bool { return x.isFinite && y.isFinite && z.isFinite && w.isFinite }
  var allZero: Bool { return x.isNormal && y.isNormal && z.isNormal && w.isNormal }
  var anySubnormal: Bool { return x.isSubnormal || y.isSubnormal || z.isSubnormal || w.isSubnormal}
  var anyInfite: Bool { return x.isInfinite || y.isInfinite || z.isInfinite || w.isInfinite}
  var anyNaN: Bool { return x.isNaN || y.isNaN || z.isNaN || w.isNaN}
  var norm: V4 { return self / self.len }
  var clampToUnit: V4 { return V4(clamp(x, min: 0, max: 1), clamp(y, min: 0, max: 1), clamp(z, min: 0, max: 1), clamp(w, min: 0, max: 1)) }
  var toU8Pixel: VU8Type { return VU8Type(U8(clamp(x * 255, min: 0, max: 255)), U8(clamp(y * 255, min: 0, max: 255)), U8(clamp(z * 255, min: 0, max: 255)), U8(clamp(w * 255, min: 0, max: 255))) }
  var heading: Scalar { return atan2(y, x) }

  func dot(_ b: V4) -> Scalar { return (x * b.x) + (y * b.y) + (z * b.z) + (w * b.w) }
  func angle(_ b: V4) -> Scalar { return acos(self.dot(b) / (self.len * b.len)) }
  func lerp(_ b: V4, _ t: Scalar) -> V4 { return self * (1 - t) + b * t }

  func cross(_ b: V4) -> V4 { return V4(
  y * b.z - z * b.y,
  z * b.x - x * b.z,
  x * b.y - y * b.x,
  0
)}

}

func +(a: V4, b: V4) -> V4 { return V4(a.x + b.x, a.y + b.y, a.z + b.z, a.w + b.w) }
func -(a: V4, b: V4) -> V4 { return V4(a.x - b.x, a.y - b.y, a.z - b.z, a.w - b.w) }
func *(a: V4, b: V4) -> V4 { return V4(a.x * b.x, a.y * b.y, a.z * b.z, a.w * b.w) }
func /(a: V4, b: V4) -> V4 { return V4(a.x / b.x, a.y / b.y, a.z / b.z, a.w / b.w) }
func +(a: V4, s: Flt) -> V4 { return V4(a.x + s, a.y + s, a.z + s, a.w + s) }
func -(a: V4, s: Flt) -> V4 { return V4(a.x - s, a.y - s, a.z - s, a.w - s) }
func *(a: V4, s: Flt) -> V4 { return V4(a.x * s, a.y * s, a.z * s, a.w * s) }
func /(a: V4, s: Flt) -> V4 { return V4(a.x / s, a.y / s, a.z / s, a.w / s) }
prefix func -(a: V4) -> V4 { return a * -1 }

